// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAowHHWuH7c-mAS_hRaVpURTaz8Yxs31G8',
    appId: '1:994673302818:web:d03f5cb02013588fe1997b',
    messagingSenderId: '994673302818',
    projectId: 'feedlog-c44af',
    authDomain: 'feedlog-c44af.firebaseapp.com',
    storageBucket: 'feedlog-c44af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfAgLgJtifbPYpB61egbKp241tg_y_1Fk',
    appId: '1:994673302818:android:d03710b6081e206de1997b',
    messagingSenderId: '994673302818',
    projectId: 'feedlog-c44af',
    storageBucket: 'feedlog-c44af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCauw_W_t_9vq_OBHn3HSJE-_ALOBDouO8',
    appId: '1:994673302818:ios:cdaa028d6246b719e1997b',
    messagingSenderId: '994673302818',
    projectId: 'feedlog-c44af',
    storageBucket: 'feedlog-c44af.firebasestorage.app',
    iosBundleId: 'com.nutriai.nutriai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCauw_W_t_9vq_OBHn3HSJE-_ALOBDouO8',
    appId: '1:994673302818:ios:cdaa028d6246b719e1997b',
    messagingSenderId: '994673302818',
    projectId: 'feedlog-c44af',
    storageBucket: 'feedlog-c44af.firebasestorage.app',
    iosBundleId: 'com.nutriai.nutriai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAowHHWuH7c-mAS_hRaVpURTaz8Yxs31G8',
    appId: '1:994673302818:web:9863a5aa730a0575e1997b',
    messagingSenderId: '994673302818',
    projectId: 'feedlog-c44af',
    authDomain: 'feedlog-c44af.firebaseapp.com',
    storageBucket: 'feedlog-c44af.firebasestorage.app',
  );
}
